### ISSUE TITLE
RequireJS 2.0 requires explicit naming of modules

### ISSUE THREAD

**Issue by chafey** [jrburke/requirejs-intellisense#4]
I played around with this today and it didn't work with RequireJS 2.0.6 unless I explicitly named the modules.  If I didn't name the modules, either Intellisense would not see the type at all or in some cases, would get the type wrong.  I then noticed that the code here is using RequireJS 1.0 so I switched to that and the problem went away.  I am guessing you already know this, but I figured I would post it to a) track it and b) let others know in case they run into the same problem.  One other thing is that the readme should state this requires VS2012 so people (like me) don't try to get it working with VS2010.  Cool project though, hope these bugs get worked out!

**Comment by jrburke** [comment]
Thanks for calling this out. I updated the readme and the require.js in this repo to 2.0.6.

**Comment by chafey** [comment]
Sure thing - you will need to explicitly name test.js for it to be visible though (person.js is already named)

**Comment by jrburke** [comment]
Right. I'm hoping we can work out the kinks so it works even with anonymous modules, since that is primarily what I use in code, and is best practice for modules. This repo is still very much in development/alpha stage.
